name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: cli/go.mod

      - name: Build
        run: go build ./...
        working-directory: cli

      - name: Test
        run: go test ./...
        working-directory: cli
